using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TodoApp.Application.Common.Dtos;
using TodoApp.Application.Common.Models;
using TodoApp.Application.TodoItems.Commands.CompleteTodoItem;
using TodoApp.Application.TodoItems.Commands.CreateTodoItem;
using TodoApp.Application.TodoItems.Commands.DeleteTodoItem;
using TodoApp.Application.TodoItems.Commands.ReopenTodoItem;
using TodoApp.Application.TodoItems.Commands.UpdateTodoItem;
using TodoApp.Application.TodoItems.Queries.GetTodoItemById;
using TodoApp.Application.TodoItems.Queries.GetTodoItems;
using TodoApp.Domain.Constants;

namespace TodoApp.Api.Controllers;

[ApiController]
[Authorize]
[Route("api/todo-items")]
[Produces("application/json")]
public sealed class TodoItemsController(ISender sender) : ControllerBase
{
    /// <summary>
    /// Returns a paged collection of items. Optional filters: listId, done,
    /// priority, overdue and search (case-insensitive title search).
    /// </summary>
    [HttpGet]
    public async Task<ActionResult<PaginatedList<TodoItemDto>>> GetTodoItems(
        [FromQuery] GetTodoItemsQuery query, CancellationToken cancellationToken) =>
        Ok(await sender.Send(query, cancellationToken));

    /// <summary>Returns a single todo item.</summary>
    [HttpGet("{id:guid}")]
    public async Task<ActionResult<TodoItemDto>> GetTodoItem(Guid id, CancellationToken cancellationToken) =>
        Ok(await sender.Send(new GetTodoItemByIdQuery(id), cancellationToken));

    /// <summary>Creates a new item inside an existing list. Returns 201 with the new id.</summary>
    [HttpPost]
    public async Task<IActionResult> CreateTodoItem(CreateTodoItemRequest request, CancellationToken cancellationToken)
    {
        var command = new CreateTodoItemCommand(
            request.ListId, request.Title, request.Note, request.Priority, request.DueDateUtc);

        var id = await sender.Send(command, cancellationToken);

        return CreatedAtAction(nameof(GetTodoItem), new { id }, new { id });
    }

    /// <summary>Updates title, note, priority and due date of an item.</summary>
    [HttpPut("{id:guid}")]
    public async Task<IActionResult> UpdateTodoItem(Guid id, UpdateTodoItemRequest request, CancellationToken cancellationToken)
    {
        var command = new UpdateTodoItemCommand(id, request.Title, request.Note, request.Priority, request.DueDateUtc);

        await sender.Send(command, cancellationToken);

        return NoContent();
    }

    /// <summary>Deletes an item.</summary>
    [HttpDelete("{id:guid}")]
    public async Task<IActionResult> DeleteTodoItem(Guid id, CancellationToken cancellationToken)
    {
        await sender.Send(new DeleteTodoItemCommand(id), cancellationToken);

        return NoContent();
    }

    /// <summary>Marks an item as done (raises a domain event).</summary>
    [HttpPost("{id:guid}/complete")]
    public async Task<IActionResult> CompleteTodoItem(Guid id, CancellationToken cancellationToken)
    {
        await sender.Send(new CompleteTodoItemCommand(id), cancellationToken);

        return NoContent();
    }

    /// <summary>Reopens a completed item.</summary>
    [HttpPost("{id:guid}/reopen")]
    public async Task<IActionResult> ReopenTodoItem(Guid id, CancellationToken cancellationToken)
    {
        await sender.Send(new ReopenTodoItemCommand(id), cancellationToken);

        return NoContent();
    }
}

/// <summary>API contract for creating an item; the id is generated by the server.</summary>
public sealed record CreateTodoItemRequest(
    Guid ListId,
    string Title,
    string? Note,
    PriorityLevel Priority,
    DateTime? DueDateUtc);

/// <summary>API contract for updating an item; the id comes from the route.</summary>
public sealed record UpdateTodoItemRequest(
    string Title,
    string? Note,
    PriorityLevel Priority,
    DateTime? DueDateUtc);
